name: me
version: 0.1.0
vision: Represent my work, projects, and blogs as a website. Clean, Clear, and Concise.
goals: []
constraints: []
techStack:
  languages:
    - HTML
    - CSS
  frameworks: []
  infrastructure: []
